name: learn-github-actions
on: [push]
jobs:
  steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
        uses: actions/checkout@v3
        run: |
          ls ${{ github.workspace }}
      - run: echo "Job Status: ${{ job.status }}."
